spring.application.name=discover_local_abilities_javaedition

spring.datasource.url=jdbc:postgresql://localhost:5432/discover_local_activities
spring.datasource.username=discover_user
spring.datasource.password=discover_password
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
